<?php

namespace elever\ClienteBundle\Entity;

use Doctrine\ORM\EntityRepository;
use PrincipalBundle\Entity\EbUsuario;

/**
 * ClienteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClienteRepository extends EntityRepository
{

	/**
	 * Metodo para buscar e retornar clientes
	 * @param array $params
	 * @param EbUsuario $user
	 * @return array |void
	 */
	public function getClientes (array $params, EbUsuario $user)
	{
		$sql = $this->createQueryBuilder("c");
		foreach ($user->getIdPerfil() as $perfil) {
			if (preg_match("/usuario/i", $perfil->getNome())) {
				$params['c.idUsuario'] = $user->getIdUsuario();
			}
		}

		$this->setFilter($params, $sql);
		return $sql->getQuery()->getArrayResult();
	}

	/**
	 * Metodo para construcao de query de busca
	 * @param array $params
	 * @param $sqlBuilder
	 * @return QueryBuilder
	 */
	private function setFilter (array $params, &$sqlBuilder)
	{
		$sqlBuilder->where("c.ativo = 1")
			->andWhere("c.excluido = 0");

		if (count($params) > 0) {
			foreach ($params as $key => $value) {
				$aux = preg_replace("/\./", "", $key);
				$sqlBuilder->andWhere("{$key} = :{$aux}")
					->setParameter("{$aux}", $value);
			}
		}
	}

}
