<?php

namespace elever\ComprasBundle\Entity;

use Doctrine\ORM\EntityRepository;
use PrincipalBundle\Entity\EbUsuario;

/**
 * SubsegmentoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubsegmentoRepository extends EntityRepository
{

	/**
	 * Metodo para buscar e retornar segmentos
	 * @param int $idSegmento
	 * @return array |void
	 */
	public function getSubsegmentoByIdSegmento ($idSegmento)
	{
		$sql = $this->createQueryBuilder("ss")
			->where("ss.ativo = 1");

		$sql->andWhere("ss.idSegmento = :idSegmento")
			->setParameter("idSegmento", $idSegmento);

		return $sql->getQuery()->getArrayResult();
	}

	/**
	 * Metodo para construcao de query de busca
	 * @param array $params
	 * @param $sqlBuilder
	 * @return QueryBuilder
	 */
	private function setFilter (array $params, &$sqlBuilder)
	{
		$sqlBuilder->where("s.ativo = 1")
			->andWhere("s.excluido = 0");

		if (count($params) > 0) {
			foreach ($params as $key => $value) {
				$aux = preg_replace("/\./", "", $key);
				$sqlBuilder->andWhere("{$key} = :{$aux}")
					->setParameter("{$aux}", $value);
			}
		}
	}


}
