security:
    encoders:
        PrincipalBundle\Entity\EbUsuario: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        elever_database:
            entity:
                class: PrincipalBundle:EbUsuario
                property: email

    firewalls:
        secured_area:
            pattern:    ^/
            form_login:
                check_path: /login_check
                login_path: /login

            logout:
                path:   /logout
                target: /login

            anonymous: ~

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/configuracao, roles: ROLE_SUPER}
        - { path: ^/, roles: ROLE_USER }
