services:
    PrincipalBundle.listener.login:
            class: PrincipalBundle\Listener\SecurityListener
            arguments: [@security.context, @session, @doctrine.orm.entity_manager]
            tags:
                - { name: kernel.event_listener, event: security.interactive_login, method: onSecurityInteractiveLogin }